name: 'sf_dbt_tpcdi'
version: '0.8.0'
config-version: 2

vars:
  benchmark: sf10000 # Configurable to: sf10, sf100, sf1000

profile: 'snowflake'





model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +transient: False

dispatch:
 - macro_namespace: dbt_utils
   search_order: ['sf_dbt_tpcdi', 'dbt_utils']
