dbsql_dbt_tpch:
  outputs:
    dev:
      catalog: main
      host: dbc-c4466db9-3ef7.cloud.databricks.com
      http_path: /sql/1.0/warehouses/b7f1482642149ac0
      schema: tpcdi_dbt
      threads: 25
      token: dapi6e910fb43183a48ab0b24c950b830827
      type: databricks
  target: dev
sql_endpoints:
  outputs:
    dev:
      catalog: main
      host: dbc-c4466db9-3ef7.cloud.databricks.com
      http_path: /sql/1.0/warehouses/b7f1482642149ac0
      method: http
      schema: tpcdi
      threads: 25
      token: dapi6e910fb43183a48ab0b24c950b830827
      type: databricks
  target: dev
